language: c

matrix:
  include:
    - name: ubuntu
      services: docker
      before_install: sudo docker build -t squad3-script-lang -f build/Dockerfile .
      script: sudo docker run -ti --net=host squad3-script-lang
